# -*- coding: utf-8 -*-
"""Regressao_Logistica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PwkrE9ZOc2_nT1KAFfkj8vPkIQop5S5y

REGRESSÃO DE TREINAMENTO

1 - DESGIN DO MODELO (INPUT. OUTPUT, FORWARD PASS)

2 - DEFINIÇÃO DA FUNÇÃO DE CUSTO E OTIMIZADOR

3 - LOOP DE TREINAMNETO

- FORWARD PASS: CALCULAR A PREDIÇÃO E O CUSTO
- BACKWARPASS: CALCULAR OS GRADIENTES
- ATUALIZAR OS PESOS
"""

import torch
 import torch.nn as nn
 import numpy as np
 import matplotlib.pyplot as plt

"""PREPARAÇÃO DOS DADOS"""

#Datapoints (NOTAS)
x_numpy = np.array([2,4,3,5,7,2,9,4,10,9,4,6,1,5,6,9,8,3,1,5,6,5,2,7,8,2,5,9,10,2,1,3,8,5,6,5])
# Classes (0 = reprovados, 1=recuperação, 2=apovados)
y_numpy = np.array([0,0,0,1,2,0,2,0,2,2,0,1,0,1,1,2,1,0,0,1,1,1,0,2,2,0,1,2,2,0,0,0,2,1,1,1])

# A principal finalidade do 'toch.from_numpy' é permitir a interoperabilidade entre
# Numpy e PyTorch, pois as duas bibliotecas têm estruturas de dados semelhantes
# (matrizes Numpy e tensores PyTorch), mas operam de forma ligeiramente diferentes.
# Isso permite que você execute operações de PyTorch com esses dados, como cálculas de
# gradientes em tensores, mesmo que os dsdo tenham sido originalmente criados em Numpy
x = torch.from_numpy(x_numpy.astype(np.float32)) # Variavel independente
y = torch.from_numpy(y_numpy.astype(np.float32)) # Variavel dependente
y = y.long() # Convertendo para inteiros de 64 bits
x = x.view(x.shape[0], 1) # Muda a dimensão do array, da horizontal para vertical

print(x.shape)
print(y.shape)
print(x)
print(y)

"""CLASS DE REGRESSÃO LOGÍSTICA"""

class RegressaoSoftmax(nn.Module):
    def __init__(self, n_input, n_output):
        super(RegressaoSoftmax, self).__init__()
        self.Linear = nn.Linear(n_input, n_output)

    def forward(self, x):
      # forward é o primeiro método que será chamado quando for criado um objeto da classe
      # RegressaoSoftmax, recebendo como parâmetro o valor que queremos estimar
        return self.Linear(x)

# DEFINIÇÃO DE MODELO
input_size = 1
output_size = 3
model = RegressaoSoftmax(input_size, output_size)

# DEFINÇÃO DA FUNÇÃO DE CUSTO E OTIMIZADOR
learning_rate = 0.05
criterion = nn.CrossEntropyLoss() # A função de custo CrossEntropyLoss inicia aplicando Softmax
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
# O Gradiente Descendente eEstocástico tem a função de atualizar os pesos
# o cálculo do grediente é uma parte crucial do treinamemto de modelos de aprendizado de máquina,
# pois permite que o modeo se ajuste aos dados, aprenda padrões e minimize a função de perda,
# tornando-o capz de fazer previsões ou  classificações mais precisas.
# O graduebte fornece informações sobre o tamanho e a direção da atualização necessária para reduzir a função de per.....

# LOOP DE TREINAMENTO
num_epochs = 1000
contador_custo = []
for epoch in range(num_epochs):
    # Forward pass and loss
    y_hat = model(x)
    loss = criterion(y_hat, y)
    contador_custo.append(loss.item())
    #print(y_hat)

    # backward pass(calcular gradientes)
    loss.backward()

    # update (atualizar os pesos)
    optimizer.step()

    # limpar o otimizador
    optimizer.zero_grad()

# PLOTANDO O GRAFICO DA FUNÇÃO DE CUSTO
print("GRÁFICO DA DUNÇÃO DE CUSTO")
plt.plot(contador_custo,'b')
plt.show()

# Fazer pedição de teste
teste = np.array([4,9,7,2,6])
t_teste = torch.from_numpy(teste.astype(np.float32))
t_teste = t_teste.view(t_teste.shape[0], 1)

# O gradiente descendente não deve ser usado na fase de teste do modelo, pois os pesos não devem ser atualizados
with torch.no_grad():
    pedicoes= model(t_teste)
    print(np.argmax(pedicoes,axis=1).flatten()) # Verificar qual o maior valor e mostrar a classe.

